### ISSUE TITLE
Treesitter-context show yaml parent keys

### ISSUE THREAD

**Issue by dzove855** [nvim-treesitter/nvim-treesitter-context#145]
Hello,

I would like know if is possible to show the parent keys of yaml file
Currently i don't see how to match with patterns.

Example:
yaml:
```
yaml:
    test:
       key:
          here: now
```
And i would like that the hover would be:
yaml.test.key when i'm on "here"
